---
title: LinkML - Linked data Modeling Language
author: linkml.org
email: support@forestry.io
description: LinkML blah....
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
