---
title: LinkML - Linked data Modeling Language
author: Chris Mungall
email: cjmungall@lbl.gov
description: LinkML is a language for modeling linked data
baseurl: ''
url: https://linkml.io/
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
